git:
    submodules: false
language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
env:
    - THOR_STREAM_TEST_PORT=8090
before_install:
    - mv .gitmodules gitmodules.old
    - sed -e 's#git@\([^:]*\):#https://\1/#' gitmodules.old > .gitmodules
    - rm gitmodules.old
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' -y ;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get update;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get install -qq g++-4.9;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.9  90;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-4.9  90;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang  clang  /usr/bin/clang-3.5  90;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++  clang++  /usr/bin/clang++-3.5  90;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.5 | head -1);sudo ln -s ${a} /usr/bin/llvm-cov;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.4 | head -1);sudo mv ${a} ${a}.old;fi
    - if [ "$TRAVIS_OS_NAME" == "osx"   -a "$CXX" == "clang++" ]; then sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-cov /usr/local/bin/llvm-cov; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then sudo chmod 777 /usr/local/lib/pkgconfig; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then brew install nginx; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -e 's/listen 8080;/listen 8090;/' /usr/local/etc/nginx/nginx.conf > tmp;fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then sudo mv tmp /usr/local/etc/nginx/nginx.conf;fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then sudo cp src/SocketStream/test/data/ThorStreamTest.html /usr/local/var/www/;fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];    then sudo nginx;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo apt-get install nginx;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sed -e 's/.*listen   80;.*/listen 8090;/'  /etc/nginx/sites-enabled/default > tmp;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo mv tmp /etc/nginx/sites-enabled/default;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo cp src/SocketStream/test/data/ThorStreamTest.html /usr/share/nginx/www/;fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ];  then sudo nginx;fi
install:
    - ./configure
script:
    - make 
branches:
  only:
      - master
      - /^feature-*$/
      - /^version-*$/

