git:
    submodules: true
language: cpp
env:
    - THOR_STREAM_TEST_PORT=8080
before_install:
    - ./.build/travis/presetup ${TRAVIS_OS_NAME}
install:
    - ./.build/travis/setup ${TRAVIS_OS_NAME}
    - sudo apt-get install npm -y
    - npm install -g http-server
    - http-server src/SocketStream/test/data/ &
script:
    - ./configure --with-boost=/tmp/extra
    - export PATH=${PATH}:$(pwd)/build/bin;export THOR_STREAM_TEST_PORT=8080;make
after_success:
    - "./CreateHeaderOnly"
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - "/^Feature-.*$/"
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
